import Foundation

/// Static emoji shortcode dictionary with search and lookup functionality.
/// Used by the composer autocomplete system to resolve `:shortcode:` patterns.
public enum EmojiShortcodes {

  public struct Match: Equatable, Sendable {
    public let shortcode: String
    public let emoji: String

    public init(shortcode: String, emoji: String) {
      self.shortcode = shortcode
      self.emoji = emoji
    }
  }

  /// Look up an exact shortcode (without colons). Case-insensitive.
  public static func lookup(_ shortcode: String) -> String? {
    shortcodes[shortcode.lowercased()]
  }

  /// Search for shortcodes matching a prefix. Requires at least 2 characters.
  /// Results are sorted with exact matches first, then alphabetically.
  public static func search(_ prefix: String, maxResults: Int = 8) -> [Match] {
    let query = prefix.lowercased()
    guard query.count >= 2 else { return [] }

    var exact: [Match] = []
    var prefixMatches: [Match] = []

    for (shortcode, emoji) in shortcodes {
      if shortcode == query {
        exact.append(Match(shortcode: shortcode, emoji: emoji))
      } else if shortcode.hasPrefix(query) {
        prefixMatches.append(Match(shortcode: shortcode, emoji: emoji))
      }
    }

    prefixMatches.sort { $0.shortcode < $1.shortcode }
    let combined = exact + prefixMatches
    return Array(combined.prefix(maxResults))
  }

  // MARK: - Shortcode Dictionary

  static let shortcodes: [String: String] = [
    // Smileys & Faces
    "smile": "😄",
    "grin": "😁",
    "grinning": "😀",
    "joy": "😂",
    "rofl": "🤣",
    "smiley": "😃",
    "sweat_smile": "😅",
    "laughing": "😆",
    "wink": "😉",
    "blush": "😊",
    "innocent": "😇",
    "slightly_smiling_face": "🙂",
    "upside_down_face": "🙃",
    "relaxed": "☺️",
    "yum": "😋",
    "relieved": "😌",
    "heart_eyes": "😍",
    "kissing_heart": "😘",
    "kissing": "😗",
    "kissing_smiling_eyes": "😙",
    "kissing_closed_eyes": "😚",
    "stuck_out_tongue_winking_eye": "😜",
    "stuck_out_tongue_closed_eyes": "😝",
    "stuck_out_tongue": "😛",
    "zany_face": "🤪",
    "money_mouth_face": "🤑",
    "hugs": "🤗",
    "nerd_face": "🤓",
    "sunglasses": "😎",
    "star_struck": "🤩",
    "partying_face": "🥳",
    "smirk": "😏",
    "unamused": "😒",
    "disappointed": "😞",
    "pensive": "😔",
    "worried": "😟",
    "confused": "😕",
    "slightly_frowning_face": "🙁",
    "frowning_face": "☹️",
    "persevere": "😣",
    "confounded": "😖",
    "tired_face": "😫",
    "weary": "😩",
    "pleading_face": "🥺",
    "cry": "😢",
    "sob": "😭",
    "triumph": "😤",
    "angry": "😠",
    "rage": "😡",
    "face_with_symbols": "🤬",
    "exploding_head": "🤯",
    "flushed": "😳",
    "hot_face": "🥵",
    "cold_face": "🥶",
    "scream": "😱",
    "fearful": "😨",
    "cold_sweat": "😰",
    "disappointed_relieved": "😥",
    "sweat": "😓",
    "thinking": "🤔",
    "shushing_face": "🤫",
    "lying_face": "🤥",
    "no_mouth": "😶",
    "neutral_face": "😐",
    "expressionless": "😑",
    "grimacing": "😬",
    "rolling_eyes": "🙄",
    "hushed": "😯",
    "astonished": "😲",
    "open_mouth": "😮",
    "sleeping": "😴",
    "drooling_face": "🤤",
    "sleepy": "😪",
    "dizzy_face": "😵",
    "zipper_mouth_face": "🤐",
    "nauseated_face": "🤢",
    "sneezing_face": "🤧",
    "mask": "😷",
    "face_with_thermometer": "🤒",
    "face_with_head_bandage": "🤕",
    "woozy_face": "🥴",
    "cowboy_hat_face": "🤠",
    "clown_face": "🤡",
    "ghost": "👻",
    "skull": "💀",
    "alien": "👽",
    "robot": "🤖",
    "poop": "💩",
    "jack_o_lantern": "🎃",

    // Gestures & Hands
    "wave": "👋",
    "raised_back_of_hand": "🤚",
    "raised_hand": "✋",
    "vulcan_salute": "🖖",
    "ok_hand": "👌",
    "pinching_hand": "🤏",
    "v": "✌️",
    "crossed_fingers": "🤞",
    "love_you_gesture": "🤟",
    "metal": "🤘",
    "call_me_hand": "🤙",
    "point_left": "👈",
    "point_right": "👉",
    "point_up_2": "👆",
    "point_down": "👇",
    "point_up": "☝️",
    "thumbsup": "👍",
    "+1": "👍",
    "thumbsdown": "👎",
    "-1": "👎",
    "fist": "✊",
    "punch": "👊",
    "left_facing_fist": "🤛",
    "right_facing_fist": "🤜",
    "clap": "👏",
    "raised_hands": "🙌",
    "open_hands": "👐",
    "palms_up": "🤲",
    "handshake": "🤝",
    "pray": "🙏",
    "writing_hand": "✍️",
    "nail_care": "💅",
    "muscle": "💪",
    "mechanical_arm": "🦾",
    "brain": "🧠",
    "salute": "🫡",

    // People & Gestures
    "shrug": "🤷",
    "facepalm": "🤦",
    "bow": "🙇",
    "see_no_evil": "🙈",
    "hear_no_evil": "🙉",
    "speak_no_evil": "🙊",

    // Hearts & Emotion
    "heart": "❤️",
    "red_heart": "❤️",
    "orange_heart": "🧡",
    "yellow_heart": "💛",
    "green_heart": "💚",
    "blue_heart": "💙",
    "purple_heart": "💜",
    "black_heart": "🖤",
    "white_heart": "🤍",
    "brown_heart": "🤎",
    "pink_heart": "🩷",
    "broken_heart": "💔",
    "two_hearts": "💕",
    "revolving_hearts": "💞",
    "heartbeat": "💓",
    "heartpulse": "💗",
    "sparkling_heart": "💖",
    "cupid": "💘",
    "gift_heart": "💝",
    "heart_decoration": "💟",
    "heavy_heart_exclamation": "❣️",
    "love_letter": "💌",
    "kiss": "💋",
    "100": "💯",
    "anger": "💢",
    "boom": "💥",
    "dizzy": "💫",
    "sweat_drops": "💦",
    "speech_balloon": "💬",
    "thought_balloon": "💭",
    "zzz": "💤",
    "fire": "🔥",
    "sparkles": "✨",
    "star": "⭐",
    "star2": "🌟",
    "zap": "⚡",
    "sunny": "☀️",
    "rainbow": "🌈",

    // Objects & Symbols
    "eyes": "👀",
    "eye": "👁️",
    "tongue": "👅",
    "lips": "👄",
    "mega": "📣",
    "loudspeaker": "📢",
    "bell": "🔔",
    "no_bell": "🔕",
    "musical_note": "🎵",
    "notes": "🎶",
    "microphone": "🎤",
    "headphones": "🎧",
    "guitar": "🎸",
    "trophy": "🏆",
    "medal": "🏅",
    "first_place_medal": "🥇",
    "second_place_medal": "🥈",
    "third_place_medal": "🥉",
    "soccer": "⚽",
    "basketball": "🏀",
    "football": "🏈",
    "baseball": "⚾",
    "tennis": "🎾",
    "tada": "🎉",
    "confetti_ball": "🎊",
    "balloon": "🎈",
    "gift": "🎁",
    "ribbon": "🎀",
    "party_popper": "🎉",
    "crystal_ball": "🔮",
    "gem": "💎",
    "crown": "👑",
    "ring": "💍",
    "moneybag": "💰",
    "money_with_wings": "💸",
    "dollar": "💵",
    "credit_card": "💳",
    "chart": "📈",
    "chart_with_downwards_trend": "📉",
    "bulb": "💡",
    "flashlight": "🔦",
    "wrench": "🔧",
    "hammer": "🔨",
    "nut_and_bolt": "🔩",
    "gear": "⚙️",
    "link": "🔗",
    "paperclip": "📎",
    "scissors": "✂️",
    "lock": "🔒",
    "unlock": "🔓",
    "key": "🔑",
    "mag": "🔍",
    "mag_right": "🔎",

    // Tech & Computing
    "computer": "💻",
    "desktop_computer": "🖥️",
    "keyboard": "⌨️",
    "phone": "📱",
    "telephone": "☎️",
    "email": "📧",
    "envelope": "✉️",
    "inbox_tray": "📥",
    "outbox_tray": "📤",
    "package": "📦",
    "memo": "📝",
    "page_facing_up": "📄",
    "page_with_curl": "📃",
    "bookmark": "🔖",
    "books": "📚",
    "book": "📖",
    "clipboard": "📋",
    "pushpin": "📌",
    "round_pushpin": "📍",
    "calendar": "📅",
    "file_folder": "📁",
    "open_file_folder": "📂",
    "wastebasket": "🗑️",
    "bug": "🐛",
    "robot_face": "🤖",

    // Travel & Transport
    "rocket": "🚀",
    "airplane": "✈️",
    "helicopter": "🚁",
    "car": "🚗",
    "taxi": "🚕",
    "bus": "🚌",
    "train": "🚆",
    "ship": "🚢",
    "anchor": "⚓",
    "earth_americas": "🌎",
    "earth_africa": "🌍",
    "earth_asia": "🌏",
    "globe_with_meridians": "🌐",
    "world_map": "🗺️",
    "house": "🏠",
    "office": "🏢",

    // Food & Drink
    "coffee": "☕",
    "tea": "🍵",
    "beer": "🍺",
    "beers": "🍻",
    "wine_glass": "🍷",
    "cocktail": "🍸",
    "tropical_drink": "🍹",
    "champagne": "🍾",
    "pizza": "🍕",
    "hamburger": "🍔",
    "fries": "🍟",
    "hotdog": "🌭",
    "taco": "🌮",
    "burrito": "🌯",
    "popcorn": "🍿",
    "ice_cream": "🍨",
    "doughnut": "🍩",
    "cookie": "🍪",
    "cake": "🎂",
    "pie": "🥧",
    "chocolate_bar": "🍫",
    "candy": "🍬",
    "apple": "🍎",
    "green_apple": "🍏",
    "banana": "🍌",
    "grapes": "🍇",
    "watermelon": "🍉",
    "strawberry": "🍓",
    "peach": "🍑",
    "mango": "🥭",
    "avocado": "🥑",
    "eggplant": "🍆",
    "corn": "🌽",
    "hot_pepper": "🌶️",
    "broccoli": "🥦",
    "egg": "🥚",
    "cheese": "🧀",

    // Animals
    "dog": "🐶",
    "cat": "🐱",
    "mouse": "🐭",
    "hamster": "🐹",
    "rabbit": "🐰",
    "fox": "🦊",
    "bear": "🐻",
    "panda": "🐼",
    "koala": "🐨",
    "tiger": "🐯",
    "lion": "🦁",
    "cow": "🐮",
    "pig": "🐷",
    "frog": "🐸",
    "monkey_face": "🐵",
    "chicken": "🐔",
    "penguin": "🐧",
    "bird": "🐦",
    "eagle": "🦅",
    "duck": "🦆",
    "owl": "🦉",
    "bat": "🦇",
    "wolf": "🐺",
    "horse": "🐴",
    "unicorn": "🦄",
    "bee": "🐝",
    "butterfly": "🦋",
    "snail": "🐌",
    "ladybug": "🐞",
    "spider": "🕷️",
    "turtle": "🐢",
    "snake": "🐍",
    "lizard": "🦎",
    "octopus": "🐙",
    "whale": "🐳",
    "dolphin": "🐬",
    "fish": "🐟",
    "tropical_fish": "🐠",
    "shark": "🦈",
    "crab": "🦀",
    "shrimp": "🦐",
    "squid": "🦑",
    "dragon": "🐉",
    "dragon_face": "🐲",
    "t_rex": "🦖",
    "dinosaur": "🦕",

    // Nature & Weather
    "seedling": "🌱",
    "evergreen_tree": "🌲",
    "deciduous_tree": "🌳",
    "palm_tree": "🌴",
    "cactus": "🌵",
    "herb": "🌿",
    "shamrock": "☘️",
    "four_leaf_clover": "🍀",
    "maple_leaf": "🍁",
    "fallen_leaf": "🍂",
    "leaves": "🍃",
    "mushroom": "🍄",
    "rose": "🌹",
    "tulip": "🌷",
    "sunflower": "🌻",
    "blossom": "🌼",
    "cherry_blossom": "🌸",
    "bouquet": "💐",
    "cloud": "☁️",
    "rain": "🌧️",
    "thunder_cloud_and_rain": "⛈️",
    "snowflake": "❄️",
    "snowman": "⛄",
    "wind_blowing_face": "🌬️",
    "tornado": "🌪️",
    "fog": "🌫️",
    "ocean": "🌊",
    "droplet": "💧",
    "umbrella": "☂️",
    "volcano": "🌋",
    "moon": "🌙",
    "full_moon": "🌕",
    "crescent_moon": "🌙",
    "new_moon_with_face": "🌚",
    "full_moon_with_face": "🌝",
    "comet": "☄️",

    // Checkmarks & Symbols
    "white_check_mark": "✅",
    "heavy_check_mark": "✔️",
    "ballot_box_with_check": "☑️",
    "x": "❌",
    "negative_squared_cross_mark": "❎",
    "exclamation": "❗",
    "question_mark": "❓",
    "grey_exclamation": "❕",
    "grey_question": "❔",
    "bangbang": "‼️",
    "interrobang": "⁉️",
    "warning": "⚠️",
    "no_entry": "⛔",
    "no_entry_sign": "🚫",
    "stop_sign": "🛑",
    "recycle": "♻️",
    "infinity": "♾️",
    "arrow_right": "➡️",
    "arrow_left": "⬅️",
    "arrow_up": "⬆️",
    "arrow_down": "⬇️",
    "arrow_right_hook": "↪️",
    "leftwards_arrow_with_hook": "↩️",
    "arrows_counterclockwise": "🔄",
    "plus": "➕",
    "minus": "➖",
    "heavy_multiplication_x": "✖️",
    "heavy_division_sign": "➗",

    // Flags (common)
    "flag_us": "🇺🇸",
    "flag_gb": "🇬🇧",
    "flag_ca": "🇨🇦",
    "flag_fr": "🇫🇷",
    "flag_de": "🇩🇪",
    "flag_jp": "🇯🇵",
    "flag_kr": "🇰🇷",
    "flag_cn": "🇨🇳",
    "flag_au": "🇦🇺",
    "flag_br": "🇧🇷",
    "flag_mx": "🇲🇽",
    "flag_in": "🇮🇳",
    "flag_it": "🇮🇹",
    "flag_es": "🇪🇸",
    "checkered_flag": "🏁",
    "triangular_flag_on_post": "🚩",
    "white_flag": "🏳️",
    "rainbow_flag": "🏳️‍🌈",
    "pirate_flag": "🏴‍☠️",

    // Miscellaneous popular
    "laughing_face": "😆",
    "upside_down": "🙃",
    "melting_face": "🫠",
    "monocle_face": "🧐",
    "face_with_monocle": "🧐",
    "mind_blown": "🤯",
    "raised_eyebrow": "🤨",
    "saluting_face": "🫡",
    "thumbs_up": "👍",
    "thumbs_down": "👎",
    "ok": "👌",
    "peace": "✌️",
    "crossed_fingers_hand": "🤞",
    "pinched_fingers": "🤌",
    "chef_kiss": "🤌",
    "paw_prints": "🐾",
    "footprints": "👣",
    "moyai": "🗿",
    "skull_and_crossbones": "☠️",
    "detective": "🕵️",
    "ninja": "🥷",
    "astronaut": "🧑‍🚀",
    "construction_worker": "👷",
    "artist": "🧑‍🎨",
    "scientist": "🧑‍🔬",
    "technologist": "🧑‍💻",
    "singer": "🧑‍🎤",
    "teacher": "🧑‍🏫",
    "cook": "🧑‍🍳",
    "farmer": "🧑‍🌾",
    "pilot": "🧑‍✈️",
    "firefighter": "🧑‍🚒",
    "hourglass": "⏳",
    "alarm_clock": "⏰",
    "stopwatch": "⏱️",
    "timer_clock": "⏲️",
    "camera": "📷",
    "video_camera": "📹",
    "movie_camera": "🎥",
    "tv": "📺",
    "radio": "📻",
    "satellite": "📡",
    "battery": "🔋",
    "electric_plug": "🔌",
    "magnet": "🧲",
    "test_tube": "🧪",
    "petri_dish": "🧫",
    "dna": "🧬",
    "microscope": "🔬",
    "telescope": "🔭",
    "joystick": "🕹️",
    "shield": "🛡️",
    "crossed_swords": "⚔️",
    "bow_and_arrow": "🏹",
  ]
}
